# Generated by Django 4.1 on 2022-12-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('fecha', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.TextField(blank=True)),
            ],
        ),
    ]
